name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Playwright browsers
      run: |
         playwright install
         playwright install-deps

    - name: Run Pytest tests
      run: |
        pytest --alluredir=allure-results

    - name: Load test report history
      if: always()
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      if: always()
      uses: simple-elf/allure-report-action@v1.7
      with:
        gh_pages: allure-report
        allure_results: build/allure-results
        allure_history: allure-history

    - name: Publish test report
      uses: actions/upload-pages-artifact@v3
      if: always()
